name: Trash
main: com.github.neapovil.trash.Trash
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/Neapovil/Trash
depend:
  - CommandAPI
permissions:
  trash.command.gui:
    default: true
  trash.command.all:
    default: true
